import argparse

from pprint import pprint

from not_covered_lines.not_covered_lines import not_covered_lines

parser = argparse.ArgumentParser(description='Convert a .coverage file into a list of tuples of not covered lines')
parser.add_argument('path', help='The path to the .coverage file, which is generated by coverage.py')
args = parser.parse_args()

pprint(not_covered_lines(args.path))